services:
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
      args:
        CACHEBUST: ${CACHEBUST}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_COGNITO_REGION: ${NEXT_PUBLIC_COGNITO_REGION}
        NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${NEXT_PUBLIC_COGNITO_USER_POOL_ID}
        NEXT_PUBLIC_COGNITO_CLIENT_ID: ${NEXT_PUBLIC_COGNITO_CLIENT_ID}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
    container_name: frontend
    restart: always
    env_file:
      - ../../.env.production
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      PORT: ${FRONTEND_PORT}
