services:
  frontend:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: frontend
    restart: always
    env_file:
      - ../../.env.development
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
