services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    env_file:
      - ../../.env.development
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
      target: development
    container_name: api
    restart: always
    env_file:
      - ../../.env.development
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis
      NODE_ENV: development
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../../src:/app/src
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
